<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Sourcekin\Content\Model;

final class ContentId
{
    private $uuid;

    public static function generate(): ContentId
    {
        return new self(\Ramsey\Uuid\Uuid::uuid4());
    }

    public static function fromString(string $contentId): ContentId
    {
        return new self(\Ramsey\Uuid\Uuid::fromString($contentId));
    }

    private function __construct(\Ramsey\Uuid\UuidInterface $contentId)
    {
        $this->uuid = $contentId;
    }

    public function toString(): string
    {
        return $this->uuid->toString();
    }

    public function __toString(): string
    {
        return $this->uuid->toString();
    }

    public function equals(ContentId $other): bool
    {
        return $this->uuid->equals($other->uuid);
    }
}
