<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Sourcekin\Content\Model;

final class DocumentMeta
{
    private $key;
    private $value;

    public function __construct(Key $key, Value $value)
    {
        if (strlen($key->toString()) === 0) {
            throw new \InvalidArgumentException('Empty meta key');
        }

        $this->key = $key;
        $this->value = $value;
    }

    public function key(): Key
    {
        return $this->key;
    }

    public function value(): Value
    {
        return $this->value;
    }

    public function withKey(Key $key): DocumentMeta
    {
        return new self($key, $this->value);
    }

    public function withValue(Value $value): DocumentMeta
    {
        return new self($this->key, $value);
    }

    public static function fromArray(array $data): DocumentMeta
    {
        if (! isset($data['key']) || ! \is_string($data['key'])) {
            throw new \InvalidArgumentException("Key 'key' is missing in data array or is not a string");
        }

        $key = Key::fromString($data['key']);

        if (! isset($data['value']) || ! \is_string($data['value'])) {
            throw new \InvalidArgumentException("Key 'value' is missing in data array or is not a string");
        }

        $value = Value::fromString($data['value']);

        return new self($key, $value);
    }

    public function toArray(): array
    {
        return [
            'key' => $this->key->toString(),
            'value' => $this->value->toString(),
        ];
    }
}
