<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Sourcekin\Content\Model;

final class DocumentId
{
    private $uuid;

    public static function generate(): DocumentId
    {
        return new self(\Ramsey\Uuid\Uuid::uuid4());
    }

    public static function fromString(string $documentId): DocumentId
    {
        return new self(\Ramsey\Uuid\Uuid::fromString($documentId));
    }

    private function __construct(\Ramsey\Uuid\UuidInterface $documentId)
    {
        $this->uuid = $documentId;
    }

    public function toString(): string
    {
        return $this->uuid->toString();
    }

    public function __toString(): string
    {
        return $this->uuid->toString();
    }

    public function equals(DocumentId $other): bool
    {
        return $this->uuid->equals($other->uuid);
    }
}
