<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Sourcekin\Content\Model;

final class Index
{
    private $index;

    public function __construct(int $index)
    {
        if ($index < 0) {
            throw new \InvalidArgumentException('Only positive integers are allowed');
        }

        $this->index = $index;
    }

    public function index(): int
    {
        return $this->index;
    }

    public function withIndex(int $index): Index
    {
        return new self($index);
    }

    public static function fromScalar(int $index): Index
    {
        return new self($index);
    }

    public function toScalar(): int
    {
        return $this->index;
    }

    public function equals(Index $index): bool
    {
        if (\get_class($this) !== \get_class($index)) {
            return false;
        }

        return $this->index === $index->index;
    }
}
