<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Sourcekin\Components\Rendering\Model;

use Sourcekin\Components\Rendering\Model\ContentType;

final class Content
{
   protected $payload = [];

    /**
     * Content constructor.
     *
     * @param array $payload
     */
    public function __construct(array $payload) { $this->payload = $payload; }

    public static function fromPayload(array $payload) {
        return new self($payload);
    }

    public function id() {
        return $this->payload['id'];
    }

    public function type() {
        return $this->payload['type'];
    }

    public function parent() {
        return $this->payload['parent']??'';
    }

    public function fields() {
        return $this->payload['fields']??[];
    }

    public function attributes() {
        return $this->payload['attributes']??[];
    }
}
