<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Sourcekin\Components\Rendering\Model;

final class ContentId
{
    private $value;

    public function isEmpty() {
        return empty($this->value);
    }

    public function __construct(string $value)
    {
        $this->value = $value;
    }

    public function value(): string
    {
        return $this->value;
    }

    public static function fromString(string $contentId): ContentId
    {
        return new self($contentId);
    }

    public function toString(): string
    {
        return $this->value;
    }

    public function __toString(): string
    {
        return $this->value;
    }

    public function equals(ContentId $contentId): bool
    {
        if (\get_class($this) !== \get_class($contentId)) {
            return false;
        }

        return $this->value === $contentId->value;
    }
}
