<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Sourcekin\Components\Rendering\Model;

final class ContentType
{
    private $value;

    public function __construct(string $value)
    {
        $this->value = $value;
    }

    public function value(): string
    {
        return $this->value;
    }

    public static function fromString(string $contentType): ContentType
    {
        return new self($contentType);
    }

    public function toString(): string
    {
        return $this->value;
    }

    public function __toString(): string
    {
        return $this->value;
    }

    public function equals(ContentType $contentType): bool
    {
        if (\get_class($this) !== \get_class($contentType)) {
            return false;
        }

        return $this->value === $contentType->value;
    }
}
