CREATE TABLE event_streams (no BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
 real_stream_name VARCHAR(150) NOT NULL,
 stream_name VARCHAR(41) NOT NULL,
 metadata LONGTEXT NOT NULL,
 category VARCHAR(150) DEFAULT NULL,
 UNIQUE INDEX idx_rsn (real_stream_name),
 INDEX idx_category (category),
 PRIMARY KEY(no)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB;
CREATE TABLE projections (no BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
 name VARCHAR(150) NOT NULL,
 position LONGTEXT NOT NULL,
 state LONGTEXT NOT NULL,
 status VARCHAR(28) NOT NULL,
 locked_until CHAR(26) DEFAULT NULL,
 UNIQUE INDEX idx_name (name),
 PRIMARY KEY(no)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB;
CREATE TABLE snapshots (aggregate_id VARCHAR(150) NOT NULL,
 aggregate_type VARCHAR(150) NOT NULL,
 last_version BIGINT UNSIGNED NOT NULL,
 created_at CHAR(26) NOT NULL,
 aggregate_root LONGBLOB DEFAULT NULL,
 INDEX idx_type (aggregate_type),
 INDEX idx_ag_id (aggregate_id),
 INDEX idx_lv (last_version),
 PRIMARY KEY(aggregate_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB